### PR TITLE
Warn tostring (#171)

### LINKED ISSUE #171: warn should call tostring on its arguments
`lemur/lib/functions/warn.lua:5: bad argument #1 to 'write' (string expected, got X)`

### PR DESCRIPTION
**Pull request by froghopperjacob**
Fixes #171 and calls tostring on its arguments

### CODE REVIEW

**Comment by froghopperjacob** [comment]
Shoot I got my previous commits tangled into this branch is this okay?

**Comment by LPGhatguy** [comment]
If you can untangle them that would be great, since one of these fixes is really straightforward and the other is a little more difficult.

**Comment by froghopperjacob** [comment]
Okay! I'll try to untangle them

**Comment by froghopperjacob** [comment]
Question: is it okay to keep those two useless commits in or should I create and another PR? (for the first I would just remove the NumberRange files since I pushed them to master instead of NumberRange branch)

**Comment by LPGhatguy** [comment]
Extra commits are no problem, we mostly squash-merge PRs anyways!

**Pull request merged**
