### PR TITLE
Add NumberRange [#155]

### PR DESCRIPTION
**Pull request by froghopperjacob**

### CODE REVIEW

**Comment by froghopperjacob** [comment]
I messed this up, Ill try to fix this.

**Comment by froghopperjacob** [comment]
I don't know if is fixed? there are still 3 commits from my previous PR but I added the commit I wanted. I think this should be fine? Just tell me and I'll close this and create a new one with the proper commit.

**Comment by LPGhatguy** [comment]
Something looks like it got messed up! You should make a new branch for each PR to avoid these kinds of mixups, it makes everything quite a bit simpler.

**Comment by froghopperjacob** [comment]
Thanks! ill do that right now.

**Pull request closed without merging**
