### PR TITLE
added Players.NumPlayers

### PR DESCRIPTION
**Pull request by aportner**

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Isn't this deprecated?

**Comment by aportner** [comment]
oh wow, you're right, it is deprecated

**Comment by aportner** [comment]
@LPGhatguy seems good! I'll need to update chat

**Comment by Kampfkarren** [comment]
@LPGhatguy #Players:GetPlayers(), specifically

**Comment by LPGhatguy** [comment]
Alright, I'll close this PR and recommend that snippet!

**Pull request closed without merging**
