### PR TITLE
Rename RunService to Run Service, like in normal Roblox

### PR DESCRIPTION
**Pull request by Kampfkarren**
For whatever reason, RunService in actual Roblox is "Run Service" (game["Run Service"]). This change emulates that behavior.

### CODE REVIEW

**Comment by LPGhatguy** [comment]
Agh, I forgot about this. This is kind of important.

Can we make `RunService` rename itself instead of telling `game` to rename `RunService`?

**Comment by Kampfkarren** [comment]
@LPGhatguy Any particular reason? Or just want to keep RunService stuff in the same file?

**Comment by LPGhatguy** [comment]
Just keeping RunService stuff isolated.

**Comment by Kampfkarren** [comment]
Done

**Comment by LPGhatguy** [comment]
And, last thing, can you add a test for RunService to validate that the name stays funky (and someone doesn't "fix" it in the future)?

**Comment by Kampfkarren** [comment]
@LPGhatguy Done!

**Comment by LPGhatguy** [comment]
Thank you! I wouldn't have caught this myself for sure.

**Comment by LPGhatguy** [comment]
This PR ended up breaking any code using `game:GetService("RunService")`. I'll be fixing that today.

**Comment by Kampfkarren** [comment]
I didn't factor that in, it's probably time to just remake GetService if that's the case (plenty of people rename services).

**Comment by LPGhatguy** [comment]
I ended up rewriting `GetService` in c8e9f2d to use `FindFirstChildOfClass` instead.

**Pull request merged**
