### PR TITLE
Coverage: LuaFileSystem not found

### PR DESCRIPTION
**Pull request by Kampfkarren**
I thought I had tried this earlier, but apparently not. More beautifully hacky tests.

I had to remove ".. lfs" since it would just result in a nil concatenation error, a silly oversight.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
*What*.
Tests on my machine work, but on Travis they don't. I'll do some more investigating on this...

**Comment by Kampfkarren** [comment]
Alright, I figured out why. Baste (rightfully) caches modules its already loaded. Busted doesn't run tests synchronously, so the import("./fs") line outside the test is run *before* the test, caches, and doesn't error since it's already imported.

**Comment by Kampfkarren** [comment]
That coverage failure tells me I have an outdated repo, I think. I'll work on it more when I can.

**Comment by Kampfkarren** [comment]
I have succumbed to my urge to not edit baste.lua. I'll probably send a PR to baste with my changes.

In essence, I just made makeImport public and made caches specific to each makeImport.

**Comment by LPGhatguy** [comment]
If `ok` is false, `lfs` will contain the error code; that _shouldn't_ be a nil concatenation error. `pcall` returns the error as the second value if the call fails. The only case where it would be nil would be if `require` threw an empty error, and it doesn't.

I don't really care about the coverage of this particular branch all that much anyways, I don't think. It's not worth emulating a broken environment to see if this branch works.

**Comment by Kampfkarren** [comment]
I forgot that pcall returned the error when I was writing the code.

As for your last paragraph, I know it doesn't really matter but luacov doesn't support ignoring a line and not having 100% just irks me.

Should the PR be closed?

**Comment by LPGhatguy** [comment]
I think I'll close this, and then hold out for a LuaCov patch that lets us ignore lines 🙂

**Pull request closed without merging**
