### PR TITLE
Rebuild instance system from the ground-up to make more sense

### PR DESCRIPTION
**Pull request by LPGhatguy**
This changelist completely rewrites Lemur's instance system.

Notably:
* Instances are now `userdata`, which makes them much more opaque
* Property definitions are static
* Clear definitions of `prototype`, `metatable`, and static methods prevent accidental extra methods on objects
* Inheritance (#8) should be much easier; for now, `IsA` is still mostly a stub.

### CODE REVIEW

**Comment by LPGhatguy** [comment]
I'm confident that tests will pass, but I do need to make sure that test coverage is decent since this is a big rewrite.

**Comment by Kampfkarren** [comment]
Wondering if this makes it harder or easier to implement Value type's Changed event (it overrides Changed from Instance), which was a real hassle for me when trying to figure out instance inheritance.

**Comment by Kampfkarren** [comment]
Fixing the coverage should be easy if you want to bother with that.

**Comment by LPGhatguy** [comment]
The office randomly lost power, I'll work on this again tomorrow, lol!

**Comment by Kampfkarren** [comment]
When this is pulled, I'll look into working on #13.

**Comment by LPGhatguy** [comment]
I think this is set; there may be follow-up commits if it breaks tests for Roact or Rodux.

**Pull request merged**
