### PR TITLE
added workspace global and made CorePackages accessible via GetService

### PR DESCRIPTION
**Pull request by aportner**

### CODE REVIEW

**Comment by LPGhatguy** [comment]
The `workspace` global is kind of strange and old and crusty. I don't think it's technically deprecated, but it's still weird.

The `CorePackages` change is simple and great!

**Comment by aportner** [comment]
@LPGhatguy seems like we use it in the apps codebase and it didn't look deprecated but I'm down to pull it out of this changelist

**Comment by aportner** [comment]
http://wiki.roblox.com/index.php?title=Global_namespace/Roblox_namespace#Variables

**Comment by Kampfkarren** [comment]
Sad to see `workspace` go, I prefer it over `game.Workspace` for its simplicity, will have to declare it myself for my own testing.

**Comment by LPGhatguy** [comment]
There's definitely room to change that idea, and not everyone agrees with how I feel about `workspace`. In general, I don't think things in general interact with Workspace more than any other service necessarily, so having a special alias is kind of strange.

**Pull request merged**
