### PR TITLE
High performance tick

### LINKED ISSUE #30: Make 'tick' use LuaSocket's socket.gettime for high performance timing
Right now, `tick` maps to `os.clock`, which only has second resolution.

We should let tick still fall back to `os.clock` if LuaSocket is missing, but we also need to have some way to figure out if the high performance timer is enabled.

### PR DESCRIPTION
**Pull request by Kampfkarren**
Closes #30.

### CODE REVIEW

**Comment by Kampfkarren** [comment]
Uh...I must be using an old git or something because of all those commits.

**Comment by LPGhatguy** [comment]
I wouldn't worry about the global for now, we can address that in a later commit.

**Comment by Kampfkarren** [comment]
I'll fix it up when I'm home then.

**Comment by Kampfkarren** [comment]
Super sorry, forgot about this! Making the changes now.

**Pull request merged**
