### PR TITLE
Color3 improvements

### PR DESCRIPTION
**Pull request by AmaranthineCodices**
This should implement all the remaining parts of Color3:

* `fromHSV`
* `toHSV`
* `lerp`
* comparing two Color3s

### CODE REVIEW

**Comment by AmaranthineCodices** [comment]
Coverage drop is because of the branches in `fromHSV` and `toHSV` v.v

It's easy to fix (different HSV/RGB colors!), but is it worth it?

**Comment by Kampfkarren** [comment]
No, I don't think you have to. I'm this close to trying to figure out how luacov works and writing a PR for it...

**Comment by Kampfkarren** [comment]
Also, can you add these to FEATURES.md?

**Comment by Kampfkarren** [comment]
👍

**Comment by LPGhatguy** [comment]
Looks good!

In the future, I want to convert these types to `userdata` to make them more opaque and line up with Roblox more closely.

**Pull request merged**
